---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalnetboxippools
  - ipaddresses
  - netboxippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalnetboxippools/finalizers
  - ipaddressclaims/finalizers
  - ipaddresses/finalizers
  - netboxippools/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalnetboxippools/status
  - ipaddressclaims/status
  - netboxippools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - ipaddressclaims
  verbs:
  - get
  - list
  - patch
  - update
  - watch
